### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by PfandleiherX** [bivashy/NanoLimboPlugin#10]
Hello, I hope you are well.
I really like using your plugin as it saves me a lot of extra Limbo servers.
A week ago NanoLimbo was updated to version 1.21. 
https://github.com/Nan1t/NanoLimbo/releases/tag/v1.8.1

_Do you think you could update NanoLimboPlugin as well?_

Please let me know if these issues bother you, I don't want to make unnecessary work for you.

**Comment by thetoxic305** [comment]
+1

**Comment by bivashy** [comment]
Hello there!
It's totally fine to open these kinds of issues. I'm not able to keep up with the latest updates in NanoLimbo, so these issues help me know when to update the plugin.
I'll update NanoLimboPlugin as soon as I can!

**Comment by bivashy** [comment]
You can now download new version
