### ISSUE TITLE
Add Limbo World Settings to Plugin Configuration

### ISSUE THREAD

**Issue by DimaSergeew** [bivashy/NanoLimboPlugin#13]
Dear Developer,

Is it possible to add settings for the Limbo world to your plugin's configuration? I am using the mcauth plugin, which temporarily creates and removes a Limbo world during user authentication. I would like to have the ability to customize the Limbo world through your plugin's configuration.

Currently, the Limbo world is automatically managed by mcauth, but being able to configure its settings would greatly enhance the flexibility and usability of the environment during the authentication process.

Thank you for considering this request. Your work on the plugin is greatly appreciated.

**Comment by bivashy** [comment]
Hi there!

I see what you want to achieve, but NanoLimboPlugin already has configuration for that purpose. If you want to make mc-auth limbos world configurable, use NanoLimbo, or **create** limbos in NanoLimboPlugin configuration instead.

mc-auth will only create a Limbo server using NanoLimboPlugin if the server **doesn't exist** in the configuration of proxy (BungeeCord `config.yml`, Velocity `velocity.toml`), so you could easily make the server configurable by adding Limbo to NanoLimboPlugin, and adding into your proxy configuration.

If you have any further questions, feel free to ask: [Discord](https://discord.com/invite/NAUbcsRZZ2), [GitHub Discussions](https://github.com/bivashy/MC-Auth-with-Link/discussions), [Spigot Discussions](https://www.spigotmc.org/threads/mc-auth-with-social-link.518966/)
