### ISSUE TITLE
(Suggestion) Server forwarding for Velocity

### ISSUE THREAD

**Issue by HarryOrWhatever** [bivashy/NanoLimboPlugin#8]
Have an option to attempt to forward the player every X seconds to a specified server.

or

Have the plugin check if a server has come back online, then send players slowly.

**Comment by bivashy** [comment]
Out of scope

I am not sure that NanoLimboPlugin should manage server connection flow, because this is only Limbo plugin without bloatware, there may be some "additional" plugin that will do that task, but I will not do that in Limbo plugin.
